"""
Neo4j knowledge-graph service.

Responsibilities:
  - Persist extracted entities/relationships as (:Entity)-[:REL]->(:Entity)
    with provenance links back to the source chunk/document.
  - Execute read-only Cypher generated by the Router/Graph agent, with a
    safety guard rejecting write clauses (defense against Cypher injection
    from a compromised prompt).
  - Provide a subgraph extraction helper the API returns to the frontend's
    Graph Visualizer component.
"""
from __future__ import annotations

import re
from typing import Any

from neo4j import AsyncGraphDatabase

from app.core.config import get_settings
from app.schemas.models import (
    ExtractedEntity, ExtractedRelationship, GraphEdge, GraphNode, GraphSubgraph,
    RetrievedChunk, RetrievalRoute,
)

settings = get_settings()

_WRITE_CLAUSES = re.compile(
    r"\b(CREATE|MERGE|DELETE|DETACH|SET|DROP|REMOVE|CALL\s+dbms|CALL\s+apoc\.create)\b",
    re.IGNORECASE,
)


class Neo4jGraphStore:
    def __init__(self):
        self.driver = AsyncGraphDatabase.driver(
            settings.NEO4J_URI, auth=(settings.NEO4J_USER, settings.NEO4J_PASSWORD)
        )

    async def close(self):
        await self.driver.close()

    async def ensure_constraints(self):
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            await session.run(
                "CREATE CONSTRAINT entity_name IF NOT EXISTS "
                "FOR (e:Entity) REQUIRE (e.name, e.type) IS UNIQUE"
            )
            await session.run(
                "CREATE CONSTRAINT chunk_id IF NOT EXISTS "
                "FOR (c:Chunk) REQUIRE c.chunk_id IS UNIQUE"
            )

    # ----------------------------------------------------------------
    # Ingestion
    # ----------------------------------------------------------------

    async def upsert_chunk_node(self, chunk_id: str, doc_id: str, text: str, chunk_index: int):
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            await session.run(
                """
                MERGE (c:Chunk {chunk_id: $chunk_id})
                SET c.doc_id = $doc_id, c.text = $text, c.chunk_index = $chunk_index
                MERGE (d:Document {doc_id: $doc_id})
                MERGE (c)-[:PART_OF]->(d)
                """,
                chunk_id=chunk_id, doc_id=doc_id, text=text, chunk_index=chunk_index,
            )

    async def upsert_extraction(
        self, chunk_id: str, entities: list[ExtractedEntity], relationships: list[ExtractedRelationship]
    ):
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            for e in entities:
                await session.run(
                    """
                    MERGE (n:Entity {name: $name, type: $type})
                    SET n.description = coalesce($description, n.description)
                    WITH n
                    MATCH (c:Chunk {chunk_id: $chunk_id})
                    MERGE (n)-[:MENTIONED_IN]->(c)
                    """,
                    name=e.name, type=e.type, description=e.description, chunk_id=chunk_id,
                )
            for r in relationships:
                await session.run(
                    """
                    MATCH (a:Entity {name: $source})
                    MATCH (b:Entity {name: $target})
                    MERGE (a)-[rel:RELATES_TO {relation: $relation}]->(b)
                    SET rel.evidence = $evidence, rel.chunk_id = $chunk_id
                    """,
                    source=r.source, target=r.target, relation=r.relation,
                    evidence=r.evidence, chunk_id=chunk_id,
                )

    # ----------------------------------------------------------------
    # Retrieval
    # ----------------------------------------------------------------

    async def run_readonly_cypher(self, cypher: str, params: dict[str, Any] | None = None) -> list[dict]:
        """
        Executes agent-generated Cypher after rejecting any write clause.
        This is the primary Cypher-injection guardrail for the Graph route.
        """
        if _WRITE_CLAUSES.search(cypher):
            raise ValueError("Rejected: generated Cypher contains a write/administrative clause.")
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            result = await session.run(cypher, params or {})
            records = [r.data() async for r in result]
        return records

    async def graph_traversal_search(self, question_entities: list[str], depth: int = 2,
                                      limit: int = 15) -> tuple[list[RetrievedChunk], GraphSubgraph]:
        """Fallback structured traversal used when the LLM-generated Cypher path is skipped/fails."""
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            result = await session.run(
                f"""
                MATCH (start:Entity)
                WHERE start.name IN $names
                MATCH path = (start)-[:RELATES_TO*0..{depth}]-(related:Entity)
                OPTIONAL MATCH (related)-[:MENTIONED_IN]->(c:Chunk)
                RETURN DISTINCT related.name AS name, related.type AS type,
                       related.description AS description, c.chunk_id AS chunk_id, c.text AS text
                LIMIT $limit
                """,
                names=question_entities, limit=limit,
            )
            records = [r.data() async for r in result]

        chunks, nodes, seen_nodes = [], [], set()
        for rec in records:
            if rec.get("name") and rec["name"] not in seen_nodes:
                seen_nodes.add(rec["name"])
                nodes.append(GraphNode(
                    id=rec["name"], label=rec["name"], type=rec.get("type") or "Entity",
                    properties={"description": rec.get("description")},
                ))
            if rec.get("chunk_id"):
                chunks.append(RetrievedChunk(
                    chunk_id=rec["chunk_id"], text=rec.get("text") or "",
                    score=1.0, source=RetrievalRoute.GRAPH, metadata={"entity": rec.get("name")},
                ))

        edges = await self._edges_between([n.id for n in nodes])
        return chunks, GraphSubgraph(nodes=nodes, edges=edges)

    async def _edges_between(self, names: list[str]) -> list[GraphEdge]:
        if not names:
            return []
        async with self.driver.session(database=settings.NEO4J_DATABASE) as session:
            result = await session.run(
                """
                MATCH (a:Entity)-[r:RELATES_TO]->(b:Entity)
                WHERE a.name IN $names AND b.name IN $names
                RETURN a.name AS source, b.name AS target, r.relation AS relation
                LIMIT 100
                """,
                names=names,
            )
            return [GraphEdge(**r.data()) async for r in result]


def get_graph_store() -> Neo4jGraphStore:
    return Neo4jGraphStore()
